name: Windows release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    name: Windows build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: x86_64-pc-windows-gnu

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-pc-windows-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/x86_64-pc-windows-gnu/release/udpbd-vexfat.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
